### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerText' of null

### ISSUE THREAD

**Issue by estebanMex** [monokrome/brunch-with-brunch#4]
In /app/assets/index.html can you change order declaration files javascript after close tag body?
To fix this error Uncaught TypeError: Cannot set property 'innerText' of null

or check if dom is ready.

<code>
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8"/>
  <title>Hello World</title>

  <link href="/stylesheets/app.css" rel="stylesheet" type="text/css">
</head>

<body>
  <h1 id="hello"></h1>
  <h2>Check the console using <i>Control/Command + Shift + I</i></h2>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script src="/javascripts/app.js"></script>
  <script>require('app');</script>
</body>
</html>

</code>

thanks

**Comment by monokrome** [comment]
I'm not sure if this project works any more, but I'll try to update it. I realize that this is an old pull request as well. I haven't used GitHub much in a long time. I'm commenting to let you know that I didn't just ignore this and move along.

Since (I think?) the HTML is generated outside of this project, I'll try to update this project later today and see if its fixed.
